@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.celestial_enchantments.enchantments.range;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;