@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.celestial_enchantments.generic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;